# Generated by Django 5.0.4 on 2024-05-05 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
